# Generated by Django 5.0.3 on 2024-03-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoWorld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='continente',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
