# Generated by Django 5.0.3 on 2024-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoWorld', '0002_pais_continente'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandeira',
            name='continente',
            field=models.CharField(default='outro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bandeira',
            name='imagem',
            field=models.URLField(),
        ),
    ]
