# Generated by Django 5.0.3 on 2024-03-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoWorld', '0003_bandeira_continente_alter_bandeira_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='bandeira',
        ),
    ]
